# Generated by Django 5.0 on 2023-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_number_of_deciders_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(default='Movie', max_length=10),
        ),
    ]
